---
linters:
  disable-all: true
    - asciicheck
    - deadcode
    - errcheck
    - ineffassign
    - goimports
    - gosimple
    - govet
    - misspell
    - structcheck
    - unconvert
    - unused

linters-settings:
  govet:
    check-shadowing: false

